### ISSUE TITLE
Python error when processing layouts with rotated multilayout keys

### ISSUE THREAD

**Issue by jakobkg** [zykrah/firmware-scripts#2]
Hi there!

When uploading certain JSON to zykrah.me, parsing fails with a Python error. The JSON that fails to parse was made with KLE and has not been manually edited.

Minimal JSON that reproduces the error:
```
[{r:-15,rx:2,x:-2,a:6,w:2},"0\n\n0"],
[{x:-2},"0\n\n1","0\n\n1"]
```

Error:
```
ERROR: local variable 'x_offset' referenced before assignment

READ THE DOCUMENTATION IF YOU HAVE NOT ALREADY.
SEE https://github.com/zykrah/firmware-scripts.
```

As far as I can tell from skimming the code, the issue occurs in `converters.py` in the function `kbd_to_qmk_info()`. In the for loop on line 61 all multilayout keys are iterated over, and on line 112, if a multilayout key is rotated the values `x_offset` and `y_offset` are subtracted from their rotation. These values are first assigned on line 120, so the Python parser throws an error. The fix is probably either moving the assignment of these up before line 60 so they're available during the loop iterating over multilayout keys, or using the values `ml_x_offset` and `ml_y offset` instead of `x_offset` and `y_offset`.

**Comment by jakobkg** [comment]
Changing the references to `ml_x_offset` and `ml_y_offset` fixed the issue, verified with an actual firmware:

![Fig. 1](https://user-images.githubusercontent.com/25484353/199482454-08b84020-bc55-4d41-ac38-7bdacfb43732.png)
![Fig. 2](https://user-images.githubusercontent.com/25484353/199482485-49a72300-f878-4c61-94fa-7f03b74883f9.png)

**Comment by zykrah** [comment]
Merged, thanks.
