### ISSUE TITLE
"Warning: Potential Security Risk Ahead" for the web site

### ISSUE THREAD

**Issue by PeterMortensen** [zykrah/firmware-scripts#9]
Opening the "[Click me!](https://zykrah.me/)" link on [the README page](https://github.com/zykrah/firmware-scripts/blob/main/README.md) results in:

> Warning: Potential Security Risk Ahead

Further:

> Firefox detected an issue and did not continue to zykrah.me. The website is either misconfigured or your computer clock is set to the wrong time.
>
> It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

**Comment by zykrah** [comment]
Cheers, I will have a look into it. Just has to do with the nginx reverse proxy.

**Comment by zykrah** [comment]
Resolved. Thanks for bringing it up.
